#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=96000
#SBATCH --time=48:00:00
#SBATCH --gres=gpu:t4:2

#SBATCH --job-name=
#SBATCH --account=ctb-akhanf
#SBATCH --output=/home/u2hussai/dgcnn/jobHandling/training/jobs/.%A.out
echo CMD: 
echo START_TIME: `date`
cd /home/u2hussai/dgcnn/jobHandling/training

RETURNVAL=$?
echo RETURNVAL=$RETURNVAL
echo END_TIME: `date`
exit $RETURNVAL
