#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=32000
#SBATCH --time=3:00:00
#SBATCH --job-name=dtifit_on_subjects.sh
#SBATCH --account=ctb-akhanf
#SBATCH --output=/home/u2hussai/dgcnn/jobs/dtifit_on_subjects.sh.%A.out
echo CMD: ./dtifit_on_subjects.sh /home/u2hussai/scratch/dtitraining/downsample_cut_pad//sub-176744/
echo START_TIME: `date`
cd /home/u2hussai/dgcnn
./dtifit_on_subjects.sh /home/u2hussai/scratch/dtitraining/downsample_cut_pad//sub-176744/
RETURNVAL=$?
echo RETURNVAL=$RETURNVAL
echo END_TIME: `date`
exit $RETURNVAL
