#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=32000
#SBATCH --time=24:00:00
#SBATCH --gres=gpu:t4:1

#SBATCH --job-name=experimentsS0.sh
#SBATCH --account=ctb-akhanf
#SBATCH --output=/home/u2hussai/dgcnn/jobs/experimentsS0.sh.%A.out
echo CMD: ./experimentsS0.sh 16
echo START_TIME: `date`
cd /home/u2hussai/dgcnn
./experimentsS0.sh 16
RETURNVAL=$?
echo RETURNVAL=$RETURNVAL
echo END_TIME: `date`
exit $RETURNVAL
