#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=32000
#SBATCH --time=3:00:00
#SBATCH --job-name=flattener.sh
#SBATCH --account=ctb-akhanf
#SBATCH --output=/home/u2hussai/dgcnn/jobs/flattener.sh.%A.out
echo CMD: ./flattener.sh /home/u2hussai/scratch/dtitraining/downsample_cut_pad//sub-134223
echo START_TIME: `date`
cd /home/u2hussai/dgcnn
./flattener.sh /home/u2hussai/scratch/dtitraining/downsample_cut_pad//sub-134223
RETURNVAL=$?
echo RETURNVAL=$RETURNVAL
echo END_TIME: `date`
exit $RETURNVAL
