#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=32000
#SBATCH --time=24:00:00
#SBATCH --job-name=niceData.sh
#SBATCH --account=ctb-akhanf
#SBATCH --output=/home/u2hussai/dgcnn/jobs/niceData.sh.%A.out
echo CMD: /home/u2hussai/dgcnn/scripts/niceData.sh
echo START_TIME: `date`
cd /home/u2hussai/dgcnn
/home/u2hussai/dgcnn/scripts/niceData.sh
RETURNVAL=$?
echo RETURNVAL=$RETURNVAL
echo END_TIME: `date`
exit $RETURNVAL
