#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=96000
#SBATCH --time=24:00:00
#SBATCH --gres=gpu:t4:2

#SBATCH --job-name=predictionScript.sh
#SBATCH --account=ctb-akhanf
#SBATCH --output=/home/u2hussai/dgcnn/jobs/predictionScript.sh.%A.out
echo CMD: ./predictionScript.sh
echo START_TIME: `date`
cd /home/u2hussai/dgcnn
./predictionScript.sh
RETURNVAL=$?
echo RETURNVAL=$RETURNVAL
echo END_TIME: `date`
exit $RETURNVAL
