#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=32000
#SBATCH --time=3:00:00
#SBATCH --job-name=preprocessing.sh
#SBATCH --account=ctb-akhanf
#SBATCH --output=/home/u2hussai/dgcnn/jobs/preprocessing.sh.%A.out
echo CMD: preprocessing.sh /home/u2hussai/scratch/dtitraining/downsample_cut_pad/sub-204016
echo START_TIME: `date`
cd /home/u2hussai/dgcnn
preprocessing.sh /home/u2hussai/scratch/dtitraining/downsample_cut_pad/sub-204016
RETURNVAL=$?
echo RETURNVAL=$RETURNVAL
echo END_TIME: `date`
exit $RETURNVAL
