#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=32000
#SBATCH --time=48:00:00
#SBATCH --gres=gpu:t4:2

#SBATCH --job-name=residual5d.sh
#SBATCH --account=ctb-akhanf
#SBATCH --output=/home/u2hussai/dgcnn/jobs/residual5d.sh.%A.out
echo CMD: ./residual5d.sh
echo START_TIME: `date`
cd /home/u2hussai/dgcnn
./residual5d.sh
RETURNVAL=$?
echo RETURNVAL=$RETURNVAL
echo END_TIME: `date`
exit $RETURNVAL
