#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=64000
#SBATCH --time=48:00:00
#SBATCH --gres=gpu:v100:2

#SBATCH --job-name=residualScalaars.sh
#SBATCH --account=ctb-akhanf
#SBATCH --output=/home/u2hussai/dgcnn/jobs/residualScalaars.sh.%A.out
echo CMD: ./residualScalaars.sh
echo START_TIME: `date`
cd /home/u2hussai/dgcnn
./residualScalaars.sh
RETURNVAL=$?
echo RETURNVAL=$RETURNVAL
echo END_TIME: `date`
exit $RETURNVAL
