#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=96000
#SBATCH --time=48:00:00
#SBATCH --gres=gpu:t4:2

#SBATCH --job-name=roughScalars.sh
#SBATCH --account=ctb-akhanf
#SBATCH --output=/home/u2hussai/dgcnn/jobs/roughScalars.sh.%A.out
echo CMD: ./roughScalars.sh 5
echo START_TIME: `date`
cd /home/u2hussai/dgcnn
./roughScalars.sh 5
RETURNVAL=$?
echo RETURNVAL=$RETURNVAL
echo END_TIME: `date`
exit $RETURNVAL
