#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=128000
#SBATCH --time=72:00:00
#SBATCH --gres=gpu:v100:2

#SBATCH --job-name=roughScalars.sh
#SBATCH --account=ctb-akhanf
#SBATCH --output=/home/u2hussai/dgcnn/jobs/roughScalars.sh.%A.out
echo CMD: ./roughScalars.sh 10
echo START_TIME: `date`
cd /home/u2hussai/dgcnn
./roughScalars.sh 10
RETURNVAL=$?
echo RETURNVAL=$RETURNVAL
echo END_TIME: `date`
exit $RETURNVAL
