#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=32000
#SBATCH --time=24:00:00
#SBATCH --gres=gpu:t4:1

#SBATCH --job-name=test2d.sh
#SBATCH --account=ctb-akhanf
#SBATCH --output=/home/u2hussai/dgcnn/jobs/test2d.sh.%A.out
echo CMD: ./test2d.sh
echo START_TIME: `date`
cd /home/u2hussai/dgcnn
./test2d.sh
RETURNVAL=$?
echo RETURNVAL=$RETURNVAL
echo END_TIME: `date`
exit $RETURNVAL
